@startuml
title Diagrama Componentes Grupos

package "Grupos" {

    package "Application" {
        [Command]
        [Service]
        [UseCase]
    }

    package "Domain" {
        [Error]
        [Model]
        [Repository]
    }

    package "Infrastructure" {
        [Config]
        [DB]
        [Mapper]
        [Web]
    }

}

@enduml
